let pizzaJson = [
  {
    id: 0,
    name: "Mussarela",
    img: "./assets/pizza.png",
    price: 20.19,
    sizes: ["8 Pç", "12 Pç", "16 Pç"],
    description: "Descrição Descrição Descrição Descrição Descrição Descrição Descrição",
  },
  {
    id: 1,
    name: "Calabresa",
    img: "./assets/pizza2.png",
    price: 18.0,
    sizes: ["8 Pç", "12 Pç", "16 Pç"],
    description: "Descrição Descrição Descrição Descrição Descrição Descrição Descrição",
  },
  {
    id: 2,
    name: "Quatro Queijos",
    img: "./assets/pizza3.png",
    price: 17.45,
    sizes: ["8 Pç", "12 Pç", "16 Pç"],
    description: "Descrição Descrição Descrição Descrição Descrição Descrição Descrição",
  },
  {
    id: 3,
    name: "Americana",
    img: "./assets/pizza4.png",
    price: 19.77,
    sizes: ["8 Pç", "12 Pç", "16 Pç"],
    description: "Descrição Descrição Descrição Descrição Descrição Descrição Descrição",
  },
  {
    id: 4,
    name: "Sorvete",
    img: "./assets/pizza5.png",
    price: 21.43,
    sizes: ["8 Pç", "12 Pç", "16 Pç"],
    description: "Descrição Descrição Descrição Descrição Descrição Descrição Descrição",
  },
  {
    id: 5,
    name: "Moda da Casa",
    img: "./assets/pizza6.png",
    price: 18.55,
    sizes: ["8 Pç", "12 Pç", "16 Pç"],
    description: "Descrição Descrição Descrição Descrição Descrição Descrição Descrição",
  },
  {
    id: 6,
    name: "Chocolate",
    img: "./assets/pizza7.png",
    price: 22.36,
    sizes: ["8 Pç", "12 Pç", "16 Pç"],
    description: "Descrição Descrição Descrição Descrição Descrição Descrição Descrição",
  },
];
